version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: gbt_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: goley_bhai_timber
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    healthcheck:
     test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/health"]
     interval: 10s
     timeout: 5s
     retries: 5
    build: ./backend
    container_name: gbt_app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    environment:
      PORT: 3000
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: goley_bhai_timber
      DB_PORT: 3306
    depends_on:
      - db

volumes:
  db_data:
